# Generated by Django 4.1.1 on 2022-09-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=3000, verbose_name='text')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'новое'), ('moderated', 'модерированная')], default='new', max_length=50, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'quotes',
            },
        ),
    ]
